"""create_applications_table

Revision ID: a64217f683a3
Revises: 3e0b84001da0
Create Date: 2026-07-24 19:20:24.431360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64217f683a3'
down_revision: Union[str, Sequence[str], None] = '3e0b84001da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('application_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('technical_owner', sa.String(length=255), nullable=True),
    sa.Column('technology_stack', sa.String(length=255), nullable=True),
    sa.Column('internet_facing', sa.Boolean(), nullable=True),
    sa.Column('authentication_type', sa.String(length=100), nullable=True),
    sa.Column('compliance_tags', sa.String(length=255), nullable=True),
    sa.Column('lifecycle', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_code'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
